### PR TITLE
Fix for Issue 117, setMetadata to use partialInstance Update

### LINKED ISSUE #117: Support labels on instances, and use PartialUpdateInstance
Instances support a notion of "labels" (key value pairs meaningful to users, like "project" = "myProject" or "env" = "staging").  Create and update instance should have a labels options which is basically a map of {string, string}.

Also, instance.setMetadata should use "PartialUpdateInstance" instead of "UpdateInstance"

### PR DESCRIPTION
**Pull request by muraliQlogic**
Fixes #117  (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by muraliQlogic** [comment]
This pull request contains changes for all review comments on [PR#146](https://github.com/googleapis/nodejs-bigtable/pull/146)

**Comment by sduskis** [comment]
@kolodny: this PR replaces another one you reviewed previously.  PTAL.

File: src/instance.js [hunk 1]
```diff
@@ -970,12 +971,26 @@ Instance.prototype.setMetadata = function(metadata, gaxOptions, callback) {
...
+    instance: extend({name: this.id}, metadata),
+    updateMask: {
+      paths: [],
+    },
+  };
+
+  const fieldsForMask = ['displayName', 'type', 'labels'];
+
+  fieldsForMask.forEach(field => {
+    if (reqOpts.instance[field]) {
```
Comment (kolodny) [inline src/instance.js]: Hmm, setting the description to an empty string will probably fail since it's considered falsely. Looks like I did that in App Profile. Can you change that here? Test instead for  
`field in reqOpts.instance`

File: test/instance.js [hunk 2]
```diff
@@ -1015,12 +1015,15 @@ describe('Bigtable/Instance', function() {
 
   describe('setMetadata', function() {
     it('should provide the proper request options', function(done) {
-      var metadata = {a: 'b'};
-      var expectedMetadata = extend({name: instance.id}, metadata);
+      var metadata = {displayName: 'updateDisplayName'};
+      var expectedMetadata = {
+        instance: extend({name: instance.id}, metadata),
```
Comment (kolodny) [inline test/instance.js]: This is somewhat of a testing anti-pattern, just create the object that you expect, in this case  

```js
{
  name: instance.name,
  metadata: metadata,
}
```

**Comment by muraliQlogic** [comment]
There is already a system test for instance update using setmetadata method. Do you want me to add something specific to update mask?

**Comment by sduskis** [comment]
@muraliQlogic, can you please resolve the conflicts?

File: src/instance.js [hunk 3]
```diff
@@ -17,6 +17,7 @@
 const common = require('@google-cloud/common');
 const extend = require('extend');
 const is = require('is');
+var snakeCase = require('lodash.snakecase');
```
Comment (kolodny) [inline src/instance.js]: const

File: src/instance.js [hunk 4]
```diff
@@ -938,12 +939,25 @@ class Instance {
       callback = gaxOptions;
       gaxOptions = {};
     }
+    var reqOpts = {
```
Comment (kolodny) [inline src/instance.js]: const

**Comment by kolodny** [comment]
@sduskis  I think that was addressed with https://github.com/googleapis/nodejs-bigtable/pull/167#issuecomment-395846526

File: src/instance.js [hunk 5]
```diff
@@ -938,12 +939,25 @@ class Instance {
...
+      }
+    });
 
     this.bigtable.request(
       {
         client: 'BigtableInstanceAdminClient',
-        method: 'updateInstance',
-        reqOpts: extend({name: this.name}, metadata),
+        method: 'partialUpdateInstance',
+        reqOpts: reqOpts,
```
Comment (kolodny) [inline src/instance.js]: Use shorthand for this, this line should change to just

```js
reqOpts,
```
