### PR TITLE
Fix bad encoded filter

### LINKED ISSUE #171: utf-8/encoding bug
Please see my comments here https://github.com/googleapis/nodejs-bigtable/pull/129#pullrequestreview-118364984

Problem 1:
Binary values in key will get unexpected values using binary values in buffers. 

Problem 2:
Binary value  filters will not return any matches

Problem 3:
TransformError from getRows after inserting unique keys 0xE6 and 0xF8

#### Environment details

  - OS: macOS 10.13.4
  - Node.js version: v8.11.2
  - npm version: 5.6.0
  - `@google-cloud/bigtable` version: 0.14.0

#### Steps to reproduce

```js
async function test() {
    await bt.createTable('test', {
        families: [
            'c'
        ]
    }).catch(swallowCode(6));

    const table = bt.table('test');

    await table.mutate([
        {
            key: 'a',
            method: 'insert',
            data: {
                c: {
                    test: Buffer.from('x', 'binary')
                }
            }
        },
        {
            key: 'b',
            method: 'insert',
            data: {
                c: {
                    test: Buffer.from('æ', 'binary')
                }
            }
        },
        {
            key: Buffer.from('æ'),
            method: 'insert',
            data: {
                c: {
                    test: Buffer.from('æ', 'binary')
                }
            }
        },
        {
            key: Buffer.from('æ', 'binary'),
            method: 'insert',
            data: {
                c: {
                    test: Buffer.from('æ', 'binary')
                }
            }
        },

    ]);

    function printRow(row) {
        console.log(row.id, Buffer.from(row.id), row.data.c.test[0].value);
    }

    let rows;

    console.log('## no filter');
    [rows] = await table.getRows({
        decode: false,
        filter: [
            {
                column: {
                    cellLimit: 1
                }
            },
        ]
    });
    rows.forEach(printRow);

    console.log('## æ utf-8 filter');
    [rows] = await table.getRows({
        decode: false,
        filter: [
            {
                column: {
                    cellLimit: 1
                }
            },
            {
                value: 'æ'
            }
        ]
    });
    rows.forEach(printRow);


    console.log('## æ binary filter');
    [rows] = await table.getRows({
        decode: false,
        filter: [
            {
                column: {
                    cellLimit: 1
                }
            },
            {
                value: Buffer.from('æ', 'binary')
            }
        ]
    });
    rows.forEach(printRow);

    console.log('## x binary filter');
    [rows] = await table.getRows({
        decode: false,
        filter: [
            {
                column: {
                    cellLimit: 1
                }
            },
            {
                value: Buffer.from('x', 'binary')
            }
        ]
    });
    rows.forEach(printRow);
}
```

Output:
```
## no filter
a <Buffer 61> <Buffer 78>
b <Buffer 62> <Buffer e6>
æ <Buffer c3 a6> <Buffer e6>
� <Buffer ef bf bd> <Buffer e6>
## æ utf-8 filter
## æ binary filter
## x binary filter
a <Buffer 61> <Buffer 78>
```

### PR DESCRIPTION
**Pull request by kolodny**
Fixes #171 

We were correctly escaping a binary string but after `Filter.convertToRegExpString` was called and returned a string and we then called `Mutation.convertToBytes` with that string, which then assumed utf8 encoding. This PR keeps the filter as a buffer so that `Mutation.convertToBytes` will see it's input as a buffer and just return that buffer

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

### CODE REVIEW

File: test/filter.js [hunk 1]
```diff
@@ -85,18 +85,18 @@ describe('Bigtable/Filter', function() {
...
       var str1 = 'hello';
       var buffer = Buffer.from(str1);
       var str2 = Filter.convertToRegExpString(buffer);
 
-      assert.strictEqual(str1, str2);
+      assert.deepStrictEqual(buffer, str2);
     });
 
-    it('should convert a non-utf8 buffer to a string', function() {
+    it('should not incorrectly convert a non-utf8 buffer to a utf8 buffer', function() {
```
Comment (stephenplusplus) [inline test/filter.js]: This test name is confusing and maybe passive-aggressive? :)

Comment (kolodny) [reply test/filter.js]: Changed to be more 😄
