### PR TITLE
Smart read retries

### LINKED ISSUE #7: bigtable: retry partially failed reads and writes
_From @arbesfeld on September 14, 2016 20:58_

My calls to bigtable `getRows()` fail intermittently, so I have had to wrap all of these methods in retry blocks. I was wondering:
1. Is this flakiness expected?
2. Have you considered adding a retry mechanism to these RPCs?

Thanks!

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1595_

### PR DESCRIPTION
**Pull request by kolodny**
Fixes #7 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
~Appropriate docs were updated (if necessary)~

### CODE REVIEW

File: src/table.js [hunk 1]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
+        numRequestsMade = 0;
+        rowsRead++;
+        const row = self.row(rowData.key);
+        row.data = rowData.data;
+        next(null, row);
+      }),
+    ]);
+
+    stream.on('error', error => {
+      // TODO - DO NOT MERGE - @stephenplusplus is this unpipe needed?
```
Comment (stephenplusplus) [inline src/table.js]: Can you elaborate on the situation that would cause this, and what needs to happen?

Comment (kolodny) [reply src/table.js]: I'm not sure if an error on the `steam` will unpipe it from `retryStream`, considering that this stream could live for hours and multiple retried streams are piping to it, does this leak memory or add any significant overhead?

File: src/table.js [hunk 2]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
   }
-  const chunkTransformer = new ChunkTransformer({decode: options.decode});
-  const stream = pumpify.obj([
-    this.requestStream(grpcOpts, reqOpts),
-    chunkTransformer,
-    through.obj(function(rowData, enc, next) {
-      if (stream._ended) {
-        return next();
+
+  const retryStream = through.obj();
```
Comment (stephenplusplus) [inline src/table.js]: Let's call the stream the user is holding either just `stream` or `userStream`.

File: src/table.js [hunk 3]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
+    }
+
+    if (rowsLimit) {
+      reqOpts.rowsLimit = rowsLimit - rowsRead;
+    }
+
+    const requestStream = this.requestStream(grpcOpts, reqOpts);
+    requestStream.on('request', () => numRequestsMade++);
+
+    const stream = pumpify.obj([
```
Comment (stephenplusplus) [inline src/table.js]: Let's call this `requestStream` or `rowStream`. Ideally "requestStream" is piped to "userStream".

File: src/table.js (hunk 1 above)
Comment (stephenplusplus) [reply src/table.js]: I'm not sure what will happen internally. Calling unpipe should be safe to do.

File: src/table.js [hunk 4]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
+      objectMode: true,
+    };
+    if (lastRowKey) {
+      const lessThan = (lhs, rhs) => {
+        return (
+          Mutation.convertToBytes(lhs).compare(Mutation.convertToBytes(rhs)) ===
+          -1
+        );
+      };
+      const greaterThan = (lhs, rhs) => {
```
Comment (stephenplusplus) [inline src/table.js]: This should work:

```js
const greaterThan = (lhs, rhs) => lessThan(rhs, lhs);
```

File: src/table.js [hunk 5]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
+        return lessThan(rhs, lhs);
+      };
+      const greaterThanOrEqualTo = (lhs, rhs) => {
```
Comment (stephenplusplus) [inline src/table.js]: This should work:

```js
const greaterThanOrEqualTo = (lhs, rhs) => !lessThan(rhs, lhs);
```

File: src/table.js [hunk 6]
```diff
@@ -445,64 +450,168 @@ Table.prototype.createReadStream = function(options) {
...
+      } else {
+        // Readjust and/or remove ranges based on previous valid row reads.
+
+        // Iterate backward since items may need to be removed.
+        for (let index = ranges.length - 1; index >= 0; index--) {
+          const range = ranges[index];
+          const normalizeRangeValue = rangeSide => {
+            return is.object(rangeSide) ? rangeSide.value : rangeSide;
+          };
+          const startValue = normalizeRangeValue(range.start);
```
Comment (stephenplusplus) [inline src/table.js]: I think we can avoid the inline function `normalizeRangeValue` if we just:

```js
const startValue = range.start.value || range.start;
const endValue = range.end.value || range.end;
```

Comment (kolodny) [reply src/table.js]: It's possible for `range.start.value` to be an empty string which would cause the value to be an object. Probably not the intended behavior. Is something like this better than the current version?

```js
const startValue = is.object(range.start) ? range.start.value : range.start;
const endValue = is.object(range.end) ? range.end.value : range.end;
```

File: src/table.js (hunk 1 above)
Comment (kolodny) [reply src/table.js]: Cool, calling `.unpipe()` just to be sure.

File: src/table.js [hunk 7]
```diff
@@ -35,7 +35,12 @@ const ChunkTransformer = require('./chunktransformer.js');
 
 // See protos/google/rpc/code.proto
 // (4=DEADLINE_EXCEEDED, 10=ABORTED, 14=UNAVAILABLE)
-const RETRY_STATUS_CODES = new Set([4, 10, 14]);
+const MUTATE_ROWS_RETRYABLE_STATUS_CODES = new Set([4, 10, 14]);
+
+// TODO - DO NOT MERGE - Figure out exactly what codes need to be here. Some combination of
```
Comment (kolodny) [inline src/table.js]: @sduskis Any input for this?

File: src/table.js (hunk 6 above)
Comment (stephenplusplus) [reply src/table.js]: Sure, that LGTM.

File: src/table.js (hunk 7 above)
Comment (sduskis) [reply src/table.js]: The Java client uses the same statuses for MutateRows and ReadRows.  I'm having a bit of trouble figuring out how the HTTP codes translate... Why can't we just use gRPC status codes?

Comment (kolodny) [reply src/table.js]: [Because the commonGRPC library "helpfully" converts the grpc code back to it's HTTP equivalent](https://github.com/googleapis/nodejs-common-grpc/blob/master/src/service.js#L570)

**Comment by kolodny** [comment]
@stephenplusplus Were there any other concerns or comments you had? If not I think we're good to merge
