### PR TITLE
fix(types): overload for bigtable.getInstances

### LINKED ISSUE #564: getInstances type is incorrect: returns a Promise when callback is unspecified
#### Environment details

  - OS: macOS 10.14
  - Node.js version: v12.12.0
  - npm version: 6.11.3
  - `@google-cloud/bigtable` version: 2.2.1

#### Steps to reproduce

I have code that calls `getInstances` without defining a callback:

```ts
const [instances] = await bigtable.getInstances();
```

`getInstances` behaves according to its docstring:

> If the callback is omitted, we'll return a Promise.

...but this behavior is not reflected in its generated type, which has return type `void` and no overloads:

```ts
getInstances(gaxOptions?: any, callback?: any): void;
```

This mismatch causes eslint to complain because `void` is a non-Promise.

Screen Shot 2019-11-07 at 15 44 55

#### Proposal

Declare an overload type:

```typescript
getInstances(gaxOptions?: any, callback: any): void;
getInstances(gaxOptions?: any): Promise<Instance[]>;
```

Thanks!

### PR DESCRIPTION
**Pull request by laljikanjareeya**
While accessing `bigtable.getInstances` with `async` function, it is giving error of return type.
Added overload and related document changes.

Fixes #564

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -62,6 +64,19 @@ const PKG = require('../../package.json');
...
+export interface GetInstancesCallback {
+  (
+    err: ServiceError | null,
+    result?: Instance[] | null,
+    nextQuery?: {} | null,
+    response?: google.bigtable.admin.v2.IListInstancesResponse | null
+  ): void;
+}
+export type GetInstancesResponse = [
+  Instance[] | null,
```
Comment (callmehiphop) [inline src/index.ts]: I don't think this will ever be null, if the request fails the promise would get rejected.

File: src/index.ts [hunk 2]
```diff
@@ -62,6 +64,19 @@ const PKG = require('../../package.json');
...
+  {} | null,
+  google.bigtable.admin.v2.IListInstancesResponse | null
```
Comment (callmehiphop) [inline src/index.ts]: same as above!

File: src/index.ts [hunk 3]
```diff
@@ -588,16 +603,39 @@ export class Bigtable {
     );
   }
 
+  getInstances(callback: GetInstancesCallback): void;
+  getInstances(gaxOptions: CallOptions, callback: GetInstancesCallback): void;
+  getInstances(gaxOptions?: CallOptions): Promise<GetInstancesResponse>;
```
Comment (callmehiphop) [inline src/index.ts]: This has always been kinda fuzzy for me - is there any harm in declaring this AFTER the callback overloads? I know the official docs say to order them from most specific to least, but I don't really know if it matters here.

File: src/index.ts [hunk 4]
```diff
@@ -588,16 +603,39 @@ export class Bigtable {
...
+  /**
+   * Query object for listing instances.
+   *
+   * @typedef {object} CallOptions
```
Comment (callmehiphop) [inline src/index.ts]: I would advocate that we do not include a JSDoc typedef for this, just because if this is likely to become stale and overlooked. If anything lets use either an [`@external` tag](https://jsdoc.app/tags-external.html) or just link to the upstream docs.

File: src/index.ts [hunk 5]
```diff
@@ -610,17 +648,37 @@ export class Bigtable {
    * });
    *
    * //-
+   * // To control how many API requests are made and page through the results
+   * // manually, set `autoPaginate` to `false`.
+   * //-
```
Comment (callmehiphop) [inline src/index.ts]: This is nothing you did, but this comment style was used for a really old version of our docs. Since we're touching it we might as well update it to use `@example <caption>...</caption>`
